#!/bin/bash

uname -a
pushd /usr/lib

echo ""
echo "--------------------------------------"
echo ""
find . -name "*java*openjdk*"
echo ""
echo "--------------------------------------"
echo ""
dpkg -l --no-pager | grep openjdk
echo ""
echo "--------------------------------------"
echo ""

popd
